解决从最近任务中进入时空指针问题
AndroidRuntime: FATAL EXCEPTION: main
 Process: com.kangear.bodycompositionanalyzer, PID: 3149
 java.lang.RuntimeException: Unable to start service com.kangear.bodycompositionanalyzer.MusicService@183794b4 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference
     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2881)
     at android.app.ActivityThread.access$2100(ActivityThread.java:144)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:135)
     at android.app.ActivityThread.main(ActivityThread.java:5221)
     at java.lang.reflect.Method.invoke(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:372)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference
     at com.kangear.bodycompositionanalyzer.MusicService.onStartCommand(MusicService.java:76)
     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2864)
     at android.app.ActivityThread.access$2100(ActivityThread.java:144) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376) 
     at android.os.Handler.dispatchMessage(Handler.java:102) 
     at android.os.Looper.loop(Looper.java:135) 
     at android.app.ActivityThread.main(ActivityThread.java:5221) 
     at java.lang.reflect.Method.invoke(Native Method) 
     at java.lang.reflect.Method.invoke(Method.java:372) 
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 